// Kaizen AI Engine: Smart Priority, Procrastination Analysis, Behaviour Insights, Voice Parsing

export function calculateSmartPriority(task, behavior = null) {
  let score = 50; // baseline
  let reasons = [];

  // Postponement penalty / urgency escalation
  if (task.postponementCount >= 3) {
    score += 35;
    reasons.push(`Postponed ${task.postponementCount} times (chronic delay risk trigger)`);
  } else if (task.postponementCount > 0) {
    score += 15;
    reasons.push(`Postponed ${task.postponementCount} time(s)`);
  }

  // Due Date factor
  if (task.dueDate) {
    const today = new Date().toISOString().split("T")[0];
    const diffDays = Math.ceil((new Date(task.dueDate) - new Date(today)) / (1000 * 60 * 60 * 24));
    if (diffDays <= 0) {
      score += 40;
      reasons.push("Due today or overdue");
    } else if (diffDays <= 2) {
      score += 25;
      reasons.push(`Approaching deadline (${diffDays} days left)`);
    } else if (diffDays <= 5) {
      score += 10;
      reasons.push(`Due within the week (${diffDays} days)`);
    }
  }

  // Performance / effort factor
  if (task.estimatedMinutes > 90) {
    score += 15;
    reasons.push("High cognitive load requirement; recommend early golden-hour focus slot");
  }

  // Category weight
  if (task.category?.toLowerCase().includes("deep") || task.category?.toLowerCase().includes("work")) {
    score += 10;
  }

  let finalPriority = "medium";
  if (score >= 70) finalPriority = "high";
  else if (score < 40) finalPriority = "low";

  return {
    priority: finalPriority,
    score,
    reason: reasons.length > 0 ? reasons.join(" • ") : "Standard baseline priority based on routine analysis.",
    updatedAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  };
}

export function parseVoiceToTask(transcript) {
  const text = transcript.trim();
  const lower = text.toLowerCase();

  let priority = "medium";
  if (lower.includes("high priority") || lower.includes("urgent") || lower.includes("important") || lower.includes("asap")) {
    priority = "high";
  } else if (lower.includes("low priority") || lower.includes("whenever") || lower.includes("casual")) {
    priority = "low";
  }

  let category = "General";
  if (lower.includes("meeting") || lower.includes("code") || lower.includes("design") || lower.includes("client") || lower.includes("work")) {
    category = "Work & Deep Focus";
  } else if (lower.includes("gym") || lower.includes("health") || lower.includes("meditation") || lower.includes("doctor") || lower.includes("run")) {
    category = "Mind & Health";
  } else if (lower.includes("expense") || lower.includes("budget") || lower.includes("bill") || lower.includes("bank") || lower.includes("invoice")) {
    category = "Financial Wellness";
  } else if (lower.includes("learn") || lower.includes("read") || lower.includes("study") || lower.includes("book")) {
    category = "Knowledge & Growth";
  }

  let estimatedMinutes = 30;
  const minMatch = text.match(/(\d+)\s*(minutes|mins|min|hours|hour|hr|hrs)/i);
  if (minMatch) {
    const val = parseInt(minMatch[1], 10);
    const unit = minMatch[2].toLowerCase();
    estimatedMinutes = unit.startsWith("h") ? val * 60 : val;
  }

  // Calculate clean title by stripping voice commands
  let cleanTitle = text
    .replace(/^(add task|create task|schedule|remind me to|please add|task)\s+/i, "")
    .replace(/(high priority|urgent|low priority|medium priority)/i, "")
    .replace(/\b(tomorrow|today|next week)\b/i, "")
    .trim();

  if (!cleanTitle) {
    cleanTitle = "Voice Task: " + text.slice(0, 35);
  } else {
    cleanTitle = cleanTitle.charAt(0).toUpperCase() + cleanTitle.slice(1);
  }

  // Due date detection
  const today = new Date();
  let dueDate = today.toISOString().split("T")[0];
  if (lower.includes("tomorrow")) {
    const tom = new Date(today);
    tom.setDate(tom.getDate() + 1);
    dueDate = tom.toISOString().split("T")[0];
  } else if (lower.includes("next week")) {
    const nw = new Date(today);
    nw.setDate(nw.getDate() + 7);
    dueDate = nw.toISOString().split("T")[0];
  }

  return {
    name: cleanTitle,
    priority,
    category,
    dueDate,
    estimatedMinutes,
    status: "pending",
    performance: 0,
    postponementCount: 0,
    priorityReason: `Generated by Kaizen Voice Task Engine (${priority.toUpperCase()} priority detected from speech cues).`,
    aiSuggestedTime: "10:00 AM",
    notes: `Voice Transcription: "${transcript}"`
  };
}

export function generateAiAdvice(tasks, habits, vices, expenses) {
  const suggestions = [];
  const postponedTasks = tasks.filter(t => t.postponementCount >= 2 && t.status !== "completed");
  
  if (postponedTasks.length > 0) {
    const t = postponedTasks[0];
    suggestions.push({
      suggestionId: `SUG-${Date.now()}-1`,
      taskId: t.taskId,
      suggestedTask: `Deconstruct '${t.name}' into a 10-Minute Micro-Action`,
      suggestType: "procrastination_breaker",
      confidenceScore: 96,
      generatedDate: new Date().toISOString().split("T")[0],
      reason: `Task has been postponed ${t.postponementCount} times. Research shows lowering the friction threshold bypasses the amygdala's avoidance response.`,
      actionableSteps: [
        "Open the necessary documents or tools without committing to finishing",
        "Set a visible 10-minute timer",
        "Celebrate small initiation step to restore momentum"
      ]
    });
  }

  const activeVices = vices.filter(v => v.status === "active");
  if (activeVices.length > 0) {
    const v = activeVices[0];
    suggestions.push({
      suggestionId: `SUG-${Date.now()}-2`,
      taskId: null,
      suggestedTask: `Environmental Architecture: Reinforce Guardrails against '${v.name}'`,
      suggestType: "vice_mitigation",
      confidenceScore: 91,
      generatedDate: new Date().toISOString().split("T")[0],
      reason: `Triggers thrive on physical proximity: "${v.trigger}". Pre-commitment devices eliminate willpower exhaustion.`,
      actionableSteps: [
        `Implement replacement action: ${v.replacementAction}`,
        "Log an urge entry immediately when friction occurs",
        "Protect your current abstinence streak"
      ]
    });
  }

  // Habit consistency
  const activeHabits = habits.filter(h => h.streak > 5);
  if (activeHabits.length > 0) {
    const h = activeHabits[0];
    suggestions.push({
      suggestionId: `SUG-${Date.now()}-3`,
      taskId: null,
      suggestedTask: `Habit Stacking: Anchor next goal onto '${h.name}'`,
      suggestType: "habit_acceleration",
      confidenceScore: 93,
      generatedDate: new Date().toISOString().split("T")[0],
      reason: `Your ${h.streak}-day streak on '${h.name}' shows an established neural pathway. Stack new actions immediately after it.`,
      actionableSteps: [
        `Identify cue: Right after finishing '${h.name}'`,
        "Execute immediate micro-action (under 2 minutes)",
        "Log completion in Kaizen Daily Tracker"
      ]
    });
  }

  return suggestions;
}
